CSRPulse/Controllers/AuditorController.cs
using CSRPulse.Common;
using CSRPulse.IServices;
using CSRPulse.Model;
using CSRPulse.Models;
using CSRPulse.Services;
using CSRPulse.Services.IServices;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static CSRPulse.Common.FileHelper;


namespace CSRPulse.Controllers
{
    public class AuditorController : BaseController<AuditorController>
    {
        private readonly IAuditorServices _auditorServices;
        private readonly IProcessDocumentService _processDocument;
        private readonly IDropdownBindService _ddlService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AuditorController(IAuditorServices auditorServices, IProcessDocumentService processDocument, IWebHostEnvironment webHostEnvironment, IDropdownBindService ddlService)
        {
            _auditorServices = auditorServices;
            _processDocument = processDocument;
            _webHostEnvironment = webHostEnvironment;
            _ddlService = ddlService;
        }
        [AutoValidateAntiforgeryToken]
        public IActionResult Index()
        {
            _logger.LogInformation("AuditorController/Index");
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                _logger.LogError("Message-" + ex.Message + " StackTrace-" + ex.StackTrace + " DatetimeStamp-" + DateTime.Now);
                throw;
            }
        }

        [HttpGet]
        public async Task<PartialViewResult> GetAuditorList(Auditor auditor)
        {
            _logger.LogInformation("AuditorController/GetAuditorList");
            try
            {
                var result = await _auditorServices.GetAuditorAsync(auditor);
                return PartialView("_AuditorList", result);
            }
            catch (Exception ex)
            {
                _logger.LogError("Message-" + ex.Message + " StackTrace-" + ex.StackTrace + " DatetimeStamp-" + DateTime.Now);
                throw;
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            BindDropdowns();
            return View(new Auditor());
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(Auditor auditor)
        {
            try
            {
                _logger.LogInformation("AuditorController/Create");
                if (ModelState.IsValid)
                {
                    auditor.CreatedBy = userDetail.UserID;
                    auditor.CreatedRid = userDetail.RoleId;
                    auditor.CreatedRname = userDetail.RoleName;
                    var result = await _auditorServices.CreateAuditorAsync(auditor);
                    if (result.IsExist)
                    {
                        ModelState.AddModelError("", "Financial Audit/Impact Assessent already exists.");
                    }
                    if (result.AuditorId > 0)
                    {
                        TempData["Message"] = "Financial Audit/Impact Assessent created successfully.";
                        return RedirectToAction(nameof(Index));
                    }
                }
                BindDropdowns();
                return View(auditor);
            }
            catch (Exception ex)
            {
                _logger.LogError("Message-" + ex.Message + " StackTrace-" + ex.StackTrace + " DatetimeStamp-" + DateTime.Now);
                throw;
            }
        }

        public async Task<IActionResult> Edit(int auditorId)
        {
            try
            {
                BindDropdowns();
                var pDocument = await _processDocument.GetProcessDocuments((int)Common.ProcessDocument.AuditAgencyOnboardingDocument);
                var auditor = _auditorServices.GetAuditorById(auditorId);

                //if (pDocument != null)
                //{
                //    if (auditor.AuditorDocument == null)
                //        auditor.AuditorDocument = new List<AuditorDocument>();


                //    //foreach (var d in pDocument)
                //    //{
                //    //    if (auditor.AuditorDocument.Any(x => x.DocumentId == d.DocumentId))
                //    //    {
                //    //        auditor.AuditorDocument.Where(m => m.DocumentId == d.DocumentId).FirstOrDefault().DocumentName = d.DocumentName;
                //    //        auditor.AuditorDocument.Where(m => m.DocumentId == d.DocumentId).FirstOrDefault().Mandatory = d.Mandatory;
                //    //        auditor.AuditorDocument.Where(m => m.DocumentId == d.DocumentId).FirstOrDefault().DocumentType = d.DocumentType;
                //    //        auditor.AuditorDocument.Where(m => m.DocumentId == d.DocumentId).FirstOrDefault().DocumentMaxSize = d.DocumentMaxSize ?? 20;
                //    //    }
                //    //    else
                //    //    {
                //    //        auditor.AuditorDocument.Add(new AuditorDocument
                //    //        {
                //    //            AuditorId = auditorId,
                //    //            DocumentId = d.DocumentId,
                //    //            DocumentName = d.DocumentName,
                //    //            DocumentType = ExtensionMethods.GetUploadDocumentType(d.DocumentType),
                //    //            DocumentMaxSize = d.DocumentMaxSize ?? 20,
                //    //            Mandatory = d.Mandatory
                //    //        });
                //    //    }
                //    //}
                //}
                return View(auditor);
            }
            catch (Exception ex)
            {
                _logger.LogError("Message-" + ex.Message + " StackTrace-" + ex.StackTrace + " DatetimeStamp-" + DateTime.Now);
                throw;
            }
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(Auditor auditor,string ButtonType)
        {
            try
            {
                _logger.LogInformation("AuditorController/Edit");
                if (ModelState.IsValid)
                {
                    auditor.UpdatedBy = userDetail.CreatedBy;
                    auditor.UpdatedOn = DateTime.Now;
                    string fileName = string.Empty;
                    StringBuilder stringBuilder = new StringBuilder();
                    int flag = 0;
                    if (ButtonType == "SaveAuditorDocument")
                    {
                        if (auditor.AuditorDocument.Where(x => (x.ServerFileName == null && x.DocumentFile == null) && x.Mandatory == true).Any())
                            return Json(new { flag = 2, type = 1, msg = "select all mandatory documents", htmlData = ConvertViewToString("_AuditorDocument", auditor, true) });

                        var listAD = auditor.AuditorDocument.Where(s => s.ServerFileName != null || s.DocumentFile != null).ToList();

                        #region Check Mime Type

                        for (int i = 0; i < auditor.AuditorDocument.Count; i++)
                        {
                            if (auditor.AuditorDocument[i].DocumentFile != null)
                            {
                                if (!ValidateFileMimeType(auditor.AuditorDocument[i].DocumentFile))
                                {
                                    stringBuilder.Append($"# {i + 1} The file format of the {auditor.AuditorDocument[i].DocumentFile.FileName} file is incorrect");
                                    stringBuilder.Append("<br>");
                                    flag = 3;
                                }
                            }
                        }

                        if (stringBuilder.ToString() != "")
                        {
                            return Json(new { flag = 3, msg = stringBuilder.ToString(), htmlData = ConvertViewToString("_AuditorDocument", auditor, true) });
                        }
                        #endregion

                        //RevoveModelState
                        if (TryValidateModel(auditor.AuditorDocument))
                        {
                            var CreatedOn = DateTime.Now;
                            string SDocumentName = string.Empty;
                            for (int i = 0; i < listAD.Count; i++)
                            {
                                listAD[i].AuditorId = auditor.AuditorId;
                                listAD[i].AuditorDocumentId = 0;
                                listAD[i].CreatedOn = DateTime.UtcNow;
                                listAD[i].CreatedBy = userDetail.UserID;
                                listAD[i].CreatedRid = userDetail.RoleId;
                                listAD[i].CreatedRname = userDetail.RoleName;


                                if (listAD[i].DocumentFile != null)
                                {
                                    var filePath = DocumentUploadFilePath.AuditorFilePath;
                                    listAD[i].UploadFileName = auditor.AuditorDocument[i].DocumentFile.FileName;
                                    listAD[i].DocumentId = auditor.AuditorDocument[i].DocumentId;

                                    SDocumentName = await UploadAuditorDocument(filePath, auditor.AuditorDocument[i].DocumentFile);

                                    if (SDocumentName == "FormulaFound")
                                    {
                                        stringBuilder.Append($"# {i + 1} {auditor.AuditorDocument[i].DocumentFile.FileName} contains formula or arithmetic operators that is not allowed in system");

CSRPulse/Views/Auditor/Create.cshtml
@model CSRPulse.Model.Auditor
@{
    ViewData["Title"] = "Add New Financial Audit/Impact Assessent Agency";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CSRPulse</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Masters</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Financial Audit</a></li>
                    <li class="breadcrumb-item active">Financial Audit/Impact Assessent Agency</li>
                </ol>
            </div>
            <h4 class="page-title">Add New Financial Audit/Impact Assessent Agency</h4>
        </div>
    </div>
    <div class="col">
        <partial name="_NoteFieldsMark" />
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form method="post" asp-area="" asp-controller="Auditor" asp-action="Create">
                    @Html.AntiForgeryToken()
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="mb-3">
                            <label asp-for="AuditOrganization" class="form-label required"></label>
                            <input type="text" asp-for="AuditOrganization" class="form-control" maxlength="256" placeholder="Enter Financial Audit/Impact Assessent (max 256 characters)" autocomplete="off">
                            <span asp-validation-for="AuditOrganization" class="invalid"></span>
                        </div>
                        <div class="mb-3 col-md-6 col-sm-12">
                            <label asp-for="Email" class="form-label"></label>
                            <input type="text" asp-for="Email" class="form-control" maxlength="50" placeholder="Enter Email (max 50 characters)" autocomplete="off">
                            <span asp-validation-for="Email" class="invalid"></span>
                        </div>
                        <div class="mb-3 col-md-6 col-sm-12">
                            <label asp-for="Website" class="form-label"></label>
                            <input type="text" asp-for="Website" class="form-control" maxlength="50" placeholder="Enter Website (max 50 characters)" autocomplete="off">
                            <span asp-validation-for="Website" class="invalid"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Address" class="form-label"></label>
                            <input type="text" asp-for="Address" class="form-control" maxlength="256" placeholder="Enter Address (max 256 characters)" autocomplete="off">
                            <span asp-validation-for="Address" class="invalid"></span>
                        </div>
                        <div class="mb-3 col-md-6 col-sm-12">
                            <label asp-for="City" class="form-label"></label>
                            <input type="text" asp-for="City" class="form-control" maxlength="50" placeholder="Enter City (max 50 characters)" autocomplete="off">
                            <span asp-validation-for="City" class="invalid"></span>
                        </div>
                        <div class="mb-3 col-md-6 col-sm-12">
                            <label asp-for="PinCode" class="form-label"></label>
                            <input type="text" asp-for="PinCode" onkeypress="return onlyNumber(event)" class="form-control" maxlength="6" placeholder="Enter PIN Code (6 digit numeric number)" autocomplete="off">
                            <span asp-validation-for="PinCode" class="invalid"></span>
                        </div>
                        <div class="mb-3 col-md-6 col-sm-12">
                            <label asp-for="StateId" class="form-label required"></label>
                            <select asp-for="StateId" asp-items="@ViewBag.ddlState" aria-required="true" class="form-select">
                                <option disabled="" label="Select State" selected="" value=""></option>
                            </select>
                            <span asp-validation-for="StateId" class="invalid"></span>
                        </div>
                        <div class="mb-3 col-md-6 col-sm-12">
                            <label asp-for="Gstno" class="form-label"></label>
                            <input type="text" asp-for="Gstno" class="form-control" maxlength="20" placeholder="Enter GST Number (max 20 characters)" autocomplete="off">
                            <span asp-validation-for="Gstno" class="invalid"></span>
                        </div>
                        <div class="mb-3 col-md-6 col-sm-12">
                            <label asp-for="Pan" class="form-label"></label>
                            <input type="text" asp-for="Pan" class="form-control" maxlength="10" placeholder="Enter PAN Number" autocomplete="off">
                            <span asp-validation-for="Pan" class="invalid"></span>
                        </div>
                        <div class="mb-3 col-md-6 col-sm-12">
                            <label asp-for="IsActive" class="form-label"></label>
                            <input asp-for="IsActive" type="checkbox" id="@Model.AuditorId" data-bs-toggle="modal" data-bs-target="#info-header-modal" data-switch="success" checked="checked" />
                            <label for="@Model.AuditorId" data-on-label="Yes" data-off-label="No" class="mb-0 d-block"></label>
                            <span asp-validation-for="IsActive" class="invalid"></span>
                        </div>

                        <div class="mb-2 text-end">
                            <a asp-area="" asp-controller="Auditor" asp-action="Index" class="btn btn-light btn-sm"><i class="dripicons-reply m-1"></i> Back to list </a>
                            <button class="btn btn-primary btn-sm" type="submit"><i class=" uil-weight me-1"></i> Save </button>
                        </div>

                    </div> <!-- end card -->
                </form>
            </div> <!-- end card body-->
        </div>
    </div>
</div>

CSRPulse/Views/Auditor/Edit.cshtml
@model CSRPulse.Model.Auditor
@{
    ViewData["Title"] = "Edit Auditor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CSRPulse</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Masters</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Financial Audit</a></li>
                    <li class="breadcrumb-item active">Financial Audit/Impact Assessent Agency</li>
                </ol>
            </div>
            <h4 class="page-title">Edit Financial Audit/Impact Assessent Agency</h4>
        </div>
    </div>
    <div class="col">
        <partial name="_NoteFieldsMark" />
    </div>
</div>



<div class="card">
    <div class="card-body">
        <form data-ajax="true" data-ajax-method="POST" data-ajax-mode="replace" enctype="multipart/form-data" asp-action="Edit" asp-controller="Auditor"
              data-ajax-success="onAuditorDocument">
            @*<form method="post" asp-controller="Auditor" asp-action="Edit" enctype="multipart/form-data">*@
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AuditorId" />
            <div class="row">
                <div class="mb-3">
                    <label asp-for="AuditOrganization" class="form-label required"></label>
                    <input type="text" asp-for="AuditOrganization" class="form-control" maxlength="256" placeholder="Enter Financial Audit/Impact Assessent (max 256 characters)" autocomplete="off">
                    <span asp-validation-for="AuditOrganization" class="invalid"></span>
                </div>
                <div class="mb-3 col-md-6 col-sm-12">
                    <label asp-for="Email" class="form-label"></label>
                    <input type="text" asp-for="Email" class="form-control" maxlength="50" placeholder="Enter Email (max 50 characters)" autocomplete="off">
                    <span asp-validation-for="Email" class="invalid"></span>
                </div>
                <div class="mb-3 col-md-6 col-sm-12">
                    <label asp-for="Website" class="form-label"></label>
                    <input type="text" asp-for="Website" class="form-control" maxlength="50" placeholder="Enter Website (max 50 characters)" autocomplete="off">
                    <span asp-validation-for="Website" class="invalid"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Address" class="form-label"></label>
                    <input type="text" asp-for="Address" class="form-control" maxlength="256" placeholder="Enter Address (max 256 characters)" autocomplete="off">
                    <span asp-validation-for="Address" class="invalid"></span>
                </div>
                <div class="mb-3 col-md-6 col-sm-12">
                    <label asp-for="City" class="form-label"></label>
                    <input type="text" asp-for="City" class="form-control" maxlength="50" placeholder="Enter City (max 50 characters)" autocomplete="off">
                    <span asp-validation-for="City" class="invalid"></span>
                </div>
                <div class="mb-3 col-md-6 col-sm-12">
                    <label asp-for="PinCode" class="form-label"></label>
                    <input type="text" asp-for="PinCode" onkeypress="return onlyNumber(event)" class="form-control" maxlength="6" placeholder="Enter PIN Code (6 digit numeric number)" autocomplete="off">
                    <span asp-validation-for="PinCode" class="invalid"></span>
                </div>
                <div class="mb-3 col-md-6 col-sm-12">
                    <label asp-for="StateId" class="form-label required"></label>
                    <select asp-for="StateId" asp-items="@ViewBag.ddlState" aria-required="true" class="form-select">
                        <option disabled="" label="Select State" selected="" value=""></option>
                    </select>
                    <span asp-validation-for="StateId" class="invalid"></span>
                </div>
                <div class="mb-3 col-md-6 col-sm-12">
                    <label asp-for="Gstno" class="form-label"></label>
                    <input type="text" asp-for="Gstno" class="form-control" maxlength="20" placeholder="Enter GST Number (max 20 characters)" autocomplete="off">
                    <span asp-validation-for="Gstno" class="invalid"></span>
                </div>
                <div class="mb-3 col-md-6 col-sm-12">
                    <label asp-for="Pan" class="form-label"></label>
                    <input type="text" asp-for="Pan" class="form-control" maxlength="10" placeholder="Enter PAN Number" autocomplete="off">
                    <span asp-validation-for="Pan" class="invalid"></span>
                </div>
                <div class="mb-3 col-md-6 col-sm-12">
                    <label asp-for="IsActive" class="form-label"></label>
                    <input asp-for="IsActive" type="checkbox" id="@Model.AuditorId" data-bs-toggle="modal" data-bs-target="#info-header-modal" data-switch="success" checked="checked" />
                    <label for="@Model.AuditorId" data-on-label="Yes" data-off-label="No" class="mb-0 d-block"></label>
                    <span asp-validation-for="IsActive" class="invalid"></span>
                </div>
                <div class="mb-3">
                    <h5>Document List</h5>
                </div>
                <div class="mb-6 text-end">
                    <button class="btn btn-danger btn-sm" type="button" onclick="AddDocument()" data-bs-toggle="tooltip" data-bs-placement="top" title="Click here, to Add New Document"><i class="mdi mdi-plus me-1"></i>Add Document</button>
                    <button class="btn btn-success btn-sm" type="submit" name="ButtonType" value="SaveAuditorDocument" id="btnSave"><i class=" uil-weight me-1"></i> Save</button>
                </div>

                <div id="div-auditordocument-grid">
                    @{ await Html.RenderPartialAsync("_AuditorDocument", Model); }
                </div>

                <div class="mb-2 text-end">
                    <a asp-area="" asp-controller="Auditor" asp-action="Index" class="btn btn-light btn-sm"><i class="dripicons-reply m-1"></i> Back to list </a>
                    <button class="btn btn-primary btn-sm" type="submit"><i class=" uil-weight me-1"></i> Update </button>
                </div>


            </div> <!-- end card -->
        </form>
    </div> <!-- end card body-->
</div>

<form data-ajax="true" data-ajax-method="POST" method="Post" asp-action="AddDocument" asp-controller="Auditor" asp-area=""
      data-ajax-success="onAddDocument">
    <div id="add-document-div">
        @{await Html.RenderPartialAsync("_AddDocument", new DocumentModel()); }
    </div>
</form>
<script type="text/javascript">
    function onAuditorDocument(data) {
        $("#div-auditordocument-grid").html(data.htmlData);
        if (data.flag == 1) {
            commonMessage('success', 'Auditor Document Saved Successfully.');
        }
        else if (data.flag == 2) {
            commonMessage('warning', data.msg);
        }
       
    }
     function AddDocument() {
            $.ajax({
            type: 'GET',
            dataType: 'JSON',
                url: '@Url.Action("AddDocument", "Auditor", new { Area=""})',
                data: { auditorId: @Model.AuditorId },
                success: function (data) {
                    $("#add-document-div").html(data.htmlData);
                    $('#add-document-modal').modal('show');
            },
            error: function (data) {
                commonMessage('error', 'Documents loading failed!');
            }
        });
    }

    function onAddDocument(data) {
        if (data.flag == 1 || data.flag == 2) {
            $("#div-auditordocument-grid").html(data.htmlData);
            $('#add-document-modal').modal('hide');
            commonMessage('success', data.msg);
        }
        else {
            commonMessage('error', 'Document adding failed!');
        }
    }
</script>

CSRPulse/Views/Auditor/_AuditorDocument.cshtml
@model Auditor
<div class="mb-3">
    <table class="table table-hover table-sm table-centered mb-0">
        <thead class="table-light">
            <tr>
                <th>#</th>
                <th>Document Name</th>
                <th>File Name</th>
                <th></th>
                <th>Remark</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.AuditorDocument != null)
            {
                for (int i = 0; i < Model.AuditorDocument.Count; i++)
                {
                    <tr>
                        <td>
                            <span>@(i+1).</span>
                            <input type="hidden" asp-for="@Model.AuditorDocument[i].DocumentId" />
                            <input type="hidden" asp-for="@Model.AuditorDocument[i].ServerFileName" />
                            <input type="hidden" asp-for="@Model.AuditorDocument[i].UploadFileName" />
                            <input type="hidden" asp-for="@Model.AuditorDocument[i].DocumentName" />
                            <input type="hidden" asp-for="@Model.AuditorDocument[i].DocumentType" />
                            <input type="hidden" asp-for="@Model.AuditorDocument[i].DocumentMaxSize" />
                            <input type="hidden" asp-for="@Model.AuditorDocument[i].Mandatory" />
                        </td>
                        <td><a data-bs-toggle="tooltip" data-bs-html="true" title="@String.Format("<b>Allow document Types:</b> {0}\n <b>Maximum  Size:</b> {1}", Model.AuditorDocument[i].DocumentType,Model.AuditorDocument[i].DocumentMaxSize)">@Model.AuditorDocument[i].DocumentName</a><span class="@(Model.AuditorDocument[i].Mandatory==true?"required":"")"></span></td>
                        <td><a id="lnk_@i" data-bs-toggle="tooltip" data-bs-placement="top" title="Download document" asp-controller="Auditor" asp-action="DownloadDocument" asp-route-fileName="@Model.AuditorDocument[i].ServerFileName">@Model.AuditorDocument[i].UploadFileName</a></td>
                        <td>
                            @if (Model.AuditorDocument[i].ServerFileName == null)
                            {
                                <input asp-for="@Model.AuditorDocument[i].DocumentFile" onchange="Filevalidation(this)">
                            }
                            else
                            {
                                <input asp-for="@Model.AuditorDocument[i].DocumentFile" disabled>

                            }
                        </td>
                        <td><input type="text" asp-for="@Model.AuditorDocument[i].Remark" class="form-control form-control-sm" maxlength="256" placeholder="You can enter max 256 characters" autocomplete="off"></td>
                        <th>
                            @if (Model.AuditorDocument[i].ServerFileName != null && Model.AuditorDocument[i].AuditorDocumentId > 0)
                            {
                                <a class="font-16 delete-link action-icon" id="delete-link_@i" data-bs-toggle="tooltip" data-bs-placement="top" title="Click here, to delete record">
                                    <i class="dripicons-trash text-danger" aria-hidden="true"></i>
                                </a>
                                <div class="delete-confirm text-nowrap" id="delete-confirm_@i" style="display: none">
                                    <a class="confirm-delete text-danger" data-ajax="true" data-ajax-method="GET" data-ajax-update="#div-auditordocument-grid"
                                       data-ajax-mode="replace" asp-action="RemoveAuditorDocument" asp-route-adId="@(Model.AuditorDocument[i].AuditorDocumentId)" asp-route-aId="@(Model.AuditorId)" asp-route-fName="@(Model.AuditorDocument[i].ServerFileName)" asp-controller="Auditor">
                                        Yes
                                    </a> <text>|</text> <a class="delete-cancel text-dark" id="delete-cancel_@i" style="cursor: pointer">No</a>
                                </div>
                            }
                        </th>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>


<script type="text/javascript">
   
</script>

CSRPulse/Views/Auditor/_AuditorList.cshtml
@model IEnumerable<Auditor>
<div class="card">
    <div class="card-body">
        <div class="text-end">
            <a asp-area="" asp-controller="Auditor" asp-action="Create" class="btn btn-danger btn-sm btn-rounded mb-3"><i class="mdi mdi-plus-circle me-1"></i> Add New Auditor</a>
        </div>
        <table class="basic-datatable table table-centered table-hover w-100 dt-responsive nowrap dataTable no-footer dtr-inline">
            <thead class="thead-light">
                <tr>
                    <th width="5%">#</th>
                    <th>@Html.DisplayNameFor(model => model.AuditOrganization)</th>
                    <th>@Html.DisplayNameFor(model => model.Email)</th>
                    <th>@Html.DisplayNameFor(model => model.Website)</th>
                    <th width="5%">@Html.DisplayNameFor(model => model.IsActive)</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() > 0)
                {
                    @foreach (var auditor in Model)
                    {
                <tr>
                    <td>
                        <span>@(Model.ToList().IndexOf(auditor) +1)</span>
                    </td>

                    <td><span data-bs-toggle="tooltip" data-bs-placement="top" title="Click here, to edit this auditor.">  @Html.ActionLink(auditor.AuditOrganization, "Edit", "Auditor", new { AuditorId = auditor.AuditorId })</span></td>
                    <td>
                        @Html.DisplayFor(model => auditor.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(model => auditor.Website)
                    </td>
                    <td>
                        <div>
                            <input type="checkbox" id="Active_@auditor.AuditorId" data-bs-toggle="modal" data-bs-target="#info-header-modal" data-switch="success" onchange="openpopup(this)" @if (auditor.IsActive == true) { <text> checked="checked" </text> } />
                            <label for="Active_@auditor.AuditorId" data-on-label="Yes" data-off-label="No" class="mb-0 d-block"></label>
                        </div>
                    </td>
                </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="5">No Records Found</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        Basicdatatable();
    });
</script>