CSRPulse/Controllers/QuickEmailController.cs
using CSRPulse.Model;
using CSRPulse.Services;
using CSRPulse.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSRPulse.Controllers
{
    public class QuickEmailController : BaseController<QuickEmailController>
    {
        private readonly IDropdownBindService _dropdownBindService;
        private readonly IQuickEmailService _quickEmailService;
        public QuickEmailController(IDropdownBindService dropdownBindService, IQuickEmailService quickEmailService)
        {
            _dropdownBindService = dropdownBindService;
            _quickEmailService = quickEmailService;
        }
        public IActionResult Index()
        {
            QuickEmail quickEmail = new QuickEmail();
            return View(new QuickEmail());
        }


        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index(QuickEmail quickEmail)
        {
            bool Issuccess = false;
            try
            {
                if (quickEmail.ToEmails.Length == 0 && quickEmail.BccEmails.Length == 0)
                {
                    ModelState.AddModelError("", "Please specify at least one recipient");
                }
                if (ModelState.IsValid) { 
                    Issuccess = await _quickEmailService.SendEmailAsync(quickEmail);
                    if(Issuccess)
                        TempData["Message"] = "Email has been sent successfully.";
                    else 
                        TempData["Error"] = "Failed to send your message. Please try later.";

                }
                else
                    return View(quickEmail);

            }
            catch (Exception)
            {
                TempData["Error"] = "Failed to send your message Please contact the administrator.";
                return View(quickEmail);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

CSRPulse/Views/QuickEmail/Index.cshtml
@model CSRPulse.Model.QuickEmail
@inject CSRPulse.Services.IServices.IDropdownBindService _dropdownBindService
@{
    ViewData["Title"] = "Quick Email";
    Layout = "~/Views/Shared/_Layout.cshtml";

    Model.BccDropdown = Model.ToDropdown = _dropdownBindService.GetAllEmails().Select(x => new SelectListItem()
    {
        Text = x.value,
        Value = x.value
    }).ToList();
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CSRPulse</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Management</a></li>
                    <li class="breadcrumb-item active">Quick Email</li>
                </ol>
            </div>
            <h4 class="page-title">Quick Email</h4>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form asp-controller="QuickEmail" asp-action="Index" onsubmit="handleSubmit()">
                    @Html.AntiForgeryToken()
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="mb-2">
                        <div class="mb-2">
                            <label asp-for="ToEmails" class="form-label"></label>
                            @Html.ListBoxFor(model => model.ToEmails, new MultiSelectList(Model.ToDropdown, "Value", "Text"), new { @class = "custom-select multiple", multiple = "multiple", id = "ToEmails_dropdown" })
                            <span asp-validation-for="ToEmails" class="invalid"></span>
                        </div>
                    </div>

                    <div class="mb-2">
                        <label asp-for="BccEmails" class="form-label"></label>
                        @Html.ListBoxFor(model => model.BccEmails, new MultiSelectList(Model.BccDropdown, "Value", "Text"), new { @class = "custom-select multiple", multiple = "multiple", id = "BccEmails_dropdown" })
                        <span asp-validation-for="BccEmails" class="invalid"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Subject" class="form-label required"></label>
                        <input type="text" asp-for="Subject" class="form-control" placeholder="Your subject" autocomplete="off" />
                        <span asp-validation-for="Subject" class="invalid"></span>
                    </div>


                    <div class="mb-2">
                        <label asp-for="Message" class="form-label required"></label>
                        <input asp-for="Message" type="hidden" class="form-control" />
                        <span asp-validation-for="Message" class="invalid"></span>
                        <div id="snow-editor" style="height: 250px;">
                        </div>
                    </div>

                    <div class="mt-2">
                        <div class="col-12 text-end">
                            <button class="btn btn-primary" type="submit">
                                Send Message <i class="mdi mdi-telegram ms-1"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@*<script src="~/assets/js/pages/demo.quilljs.js"></script>*@
<script type="text/javascript">
    function handleSubmit() {
        document.getElementById('Message').value = quill.root.innerHTML;
    };
</script>
@section Scripts{
    <script>
        var quill = new Quill('#snow-editor', {
            theme: 'snow',
            modules: {
                toolbar: [
                    [{
                        font: []
                    }, {
                        size: []
                    }],
                    ["bold", "italic", "underline", "strike"],
                    [{
                        color: []
                    }, {
                        background: []
                    }],
                    [{
                        script: "super"
                    }, {
                        script: "sub"
                    }],
                    [{
                        header: [!1, 1, 2, 3, 4, 5, 6]
                    }],
                    [{
                        list: "ordered"
                    }, {
                        list: "bullet"
                    }],
                    ["direction", {
                        align: []
                    }],

                    ["clean"]
                ]
            }
        });
        // This will set `ignore` for all validation calls
        jQuery.validator.setDefaults({
            // This will ignore all hidden elements alongside `contenteditable` elements
            // that have no `name` attribute
            ignore: ":hidden, [contenteditable='true']:not([name])"
        });
    </script>
}