CSRPulse/Controllers/DistrictController.cs
using CSRPulse.Model;
using CSRPulse.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CSRPulse.Services.IServices;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Text;
using CSRPulse.ExportImport.Interfaces;
using System.Data;
using static CSRPulse.Common.FileHelper;
using CSRPulse.Common;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using CSRPulse.Models;

namespace CSRPulse.Controllers
{
    [Route("[Controller]/[action]")]
    public class DistrictController : BaseController<DistrictController>
    {
        private readonly IDistrictServices _districtServices;
        private readonly IStateServices _stateServices;
        private readonly IDropdownBindService _ddlService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IExport _export;
        public DistrictController(IDistrictServices districtServices, IDropdownBindService ddlService, IWebHostEnvironment webHostEnvironment, IStateServices stateServices, IExport export)
        {
            _districtServices = districtServices;
            _ddlService = ddlService;
            _webHostEnvironment = webHostEnvironment;
            _stateServices = stateServices;
            _export = export;
        }

        [HttpGet]
        public IActionResult Index()
        {
            _logger.LogInformation("DistrictController/Index");
            try
            {
                BindDropdowns();
                //  var result = await _districtServices.GetDistrictList();
                return View();
            }
            catch (Exception ex)
            {
                _logger.LogError("Message-" + ex.Message + " StackTrace-" + ex.StackTrace + " DatetimeStamp-" + DateTime.Now);
                throw;
            }
        }

        [HttpGet]
        public async Task<PartialViewResult> GetDistrictList(District district)
        {
            _logger.LogInformation("DistrictController/GetDistrictList");
            try
            {
                var result = await _districtServices.GetDistrictList(district);
                return PartialView("_DistrictList", result);
            }
            catch (Exception ex)
            {
                _logger.LogError("Message-" + ex.Message + " StackTrace-" + ex.StackTrace + " DatetimeStamp-" + DateTime.Now);
                throw;
            }
        }
        [HttpGet]
        public IActionResult Create()
        {
            BindDropdowns();
            return View(new District());
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(District district)
        {
            try
            {
                _logger.LogInformation("DistrictController/Create");
                ModelState.Remove("IsActive");
                BindDropdowns();
                if (ModelState.IsValid)
                {

                    district.CreatedBy = userDetail.UserID;
                    district.CreatedRid = userDetail.RoleId;
                    district.CreatedRname = userDetail.RoleName;
                    district.IsActive = true;
                    if (await _districtServices.RecordExist(district))
                    {
                        ModelState.AddModelError("", "District or District Code already exists");
                    }
                    else
                    {
                        var result = await _districtServices.CreateDistrict(district);
                        if (district.RecordExist)
                        {
                            ModelState.AddModelError("", "District already exists");
                        }
                        if (result)
                        {
                            TempData["Message"] = "District Created Successfully.";
                            return RedirectToAction(nameof(Index));
                        }
                    }
                }
                return View(district);
            }
            catch (Exception ex)
            {
                _logger.LogError("Message-" + ex.Message + " StackTrace-" + ex.StackTrace + " DatetimeStamp-" + DateTime.Now);
                throw;
            }
        }

        public async Task<IActionResult> Edit(int rid)
        {
            try
            {
                BindDropdowns();
                var uDetail = await _districtServices.GetDistrictById(rid);
                return View(uDetail);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(District district)
        {
            try
            {
                _logger.LogInformation("DistrictController/Edit");
                ModelState.Remove("IsActive");
                BindDropdowns();
                if (ModelState.IsValid)
                {
                    district.UpdatedBy = userDetail.UserID;
                    district.UpdatedRid = userDetail.RoleId;
                    district.UpdatedRname = userDetail.RoleName;
                    district.UpdatedOn = DateTime.Now;
                    var result = await _districtServices.UpdateDistrict(district);
                    if (district.RecordExist)
                    {
                        ModelState.AddModelError("", "District already exists");
                    }
                    if (result)
                    {
                        TempData["Message"] = "District Updated Successfully.";
                        return RedirectToAction(nameof(Index));
                    }
                }
                return View(district);
            }
            catch (Exception ex)
            {
                _logger.LogError("Message-" + ex.Message + " StackTrace-" + ex.StackTrace + " DatetimeStamp-" + DateTime.Now);
                throw;
            }
        }

        [NonAction]
        void BindDropdowns()
        {
            var stateList = _ddlService.GetStateAsync(null, null);
            ViewBag.ddlState = new SelectList(stateList, "id", "value");
        }

        [HttpPost]
        public JsonResult ActiveDeActive(int id, bool isChecked)
        {
            _logger.LogInformation("UoMController/ActiveDeActive");
            var result = _districtServices.ActiveDeActive(id, isChecked);
            return Json(result);
        }

        public async Task<IActionResult> ExportTemplate()
        {

            var sPhysicalPath = Path.Combine(_webHostEnvironment.WebRootPath, DocumentUploadFilePath.TemplatesLocationFilePath + "DistrictTemplate.xlsx");

            if (!System.IO.File.Exists(sPhysicalPath))
                return Content($"Template not found.");

            return await DownloadFile(sPhysicalPath);
        }

        public async Task<IActionResult> ExportRefTemplate()
        {
            var statelist = await _stateServices.GetStateList();
            List<string> takeColumns = new List<string> { "StateId", "StateName" };
            var statedt = Common.ExtensionMethods.ToDataTable<State>(statelist);

            var dt = Common.ExtensionMethods.PrepairExportTable(statedt, takeColumns);
            DataSet ds = new DataSet();
            ds.Tables.Add(dt);

            var uploadedFilePath = Path.Combine(_webHostEnvironment.WebRootPath, DocumentUploadFilePath.TempFilePath);
            if (!Directory.Exists(uploadedFilePath))
                Directory.CreateDirectory(uploadedFilePath);

            var sPhysicalPath = Path.Combine(uploadedFilePath, ExtensionMethods.SetUniqueFileName(".xlsx"));
            if (_export.ExportToExcel(ds, sPhysicalPath, "RefrenceCode_District"))
            {
                if (!System.IO.File.Exists(sPhysicalPath))
                    return Content($"Tempfile path not found.");

                var res = await DownloadFile(sPhysicalPath);

                Common.ExtensionMethods.DeleteFile(sPhysicalPath);
                return res;

            }
            else
            {
                return Content($"District refrence code file downloding filed.");
            }
        }

        public ViewResult Import()
        {
            return View();
        }



        [HttpPost]
        public ActionResult _ImportDistrictData(IFormFile file)
        {
            _logger.LogInformation("DistrictController/_ImportDistrictData");
            try
            {
                string fileName = string.Empty; string filePath = string.Empty;
                int error = 0, warning = 0, duplicateEntries = 0;
                List<DistrictImport> importDistrictSave = new List<DistrictImport>();
                List<string> columnName = new List<string>();
                List<string> missingHeaders;
                string msg = string.Empty;
                DistrictImportModel districtImpModel = new DistrictImportModel();
                List<DistrictImport> DistrictForm = new List<DistrictImport>();

                if (file.Length > 0)
                {
                    var fileExtension = Path.GetExtension(file.FileName).ToLower();

                    if (ValidateFileMimeType(file) && fileExtension == ".xlsx")
                    {
                        fileName = Path.GetFileName(file.FileName);
                        #region Upload File At temp location===
                        fileName = ExtensionMethods.SetUniqueFileName(Path.GetFileNameWithoutExtension(file.FileName),
                               Path.GetExtension(file.FileName));

                        filePath = DocumentUploadFilePath.TempFilePath;
                        var uploadedFilePath = Path.Combine(_webHostEnvironment.WebRootPath, filePath);
                        string sPhysicalPath = Path.Combine(uploadedFilePath, fileName);

CSRPulse/Views/District/Create.cshtml
@model CSRPulse.Model.District
@{
    ViewData["Title"] = "Add New District";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CSRPulse</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Masters</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Locations</a></li>
                    <li class="breadcrumb-item active">District</li>
                </ol>
            </div>
            <h4 class="page-title">District</h4>
        </div>
    </div>
    <div class="col">
        <partial name="_NoteFieldsMark" />
    </div>
</div>

<div class="card">
    <div class="card-body">
        <form method="post" asp-controller="District" asp-action="Create">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-xxl-6 col-xl-6 col-lg-8 col-md-8 col-sm-12 col-12">
                    <div class="mb-3">
                        <label asp-for="StateId" class="form-label required"></label>
                        <select asp-for="StateId" asp-items="@ViewBag.ddlState" aria-required="true" class="form-select">
                            <option disabled="" label="Select State" selected="" value=""></option>
                        </select>
                        <span asp-validation-for="StateId" class="invalid"></span>
                    </div>


                    <div class="mb-3">
                        <label asp-for="DistrictName" class="form-label required"></label>
                        <input type="text" asp-for="DistrictName" class="form-control" maxlength="100" placeholder="Enter District Name (max 100 characters)" autocomplete="off">
                        <span asp-validation-for="DistrictName" class="invalid"></span>
                    </div>


                    <div class="mb-3">
                        <label asp-for="DistrictShort" for="UserName" class="form-label"> </label>
                        <input type="text" asp-for="DistrictShort" class="form-control" maxlength="4" placeholder="Enter Short Name (max 4 characters)" autocomplete="off">
                        <span asp-validation-for="DistrictShort" class="invalid"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="DistrictCode" class="form-label required"></label>
                        <input type="text" asp-for="DistrictCode" onkeypress="return onlyNumber(event)" class="form-control" maxlength="3" placeholder="Enter District Code (max 3 digits number)" autocomplete="off">
                        <span asp-validation-for="DistrictCode" class="invalid"></span>
                    </div>
                    <div class="mb-2 text-end">
                        <a asp-area="" asp-controller="District" asp-action="Index" class="btn btn-light btn-sm"><i class="dripicons-reply m-1"></i> Back to list </a>
                        <button class="btn btn-primary btn-sm" type="submit"><i class="uil-weight me-1"></i> Save </button>
                    </div>
                </div>

            </div> <!-- end card -->
        </form>
    </div> <!-- end card body-->
</div>

CSRPulse/Views/District/Edit.cshtml
@model CSRPulse.Model.District
@{
    ViewData["Title"] = "Edit District";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CSRPulse</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Masters</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Locations</a></li>
                    <li class="breadcrumb-item active">Edit District</li>
                </ol>
            </div>
            <h4 class="page-title">Edit District</h4>
        </div>
    </div>
    <div class="col">
        <partial name="_NoteFieldsMark" />
    </div>
</div>



<div class="card">
    <div class="card-body">
        <form method="post" asp-controller="District" asp-action="Edit">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DistrictId" />
            <div class="row">
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                    <div class="mb-3">
                        <label asp-for="StateId" class="form-label required"></label>
                        <select asp-for="StateId" asp-items="@ViewBag.ddlState" aria-required="true" class="form-select">
                            <option disabled="" label="State" selected="" value="">State</option>
                        </select>
                        <span asp-validation-for="StateId" class="invalid"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="DistrictName" class="form-label required"></label>
                        <input type="text" asp-for="DistrictName" class="form-control" maxlength="100" placeholder="Enter District Name (max 50 characters)" autocomplete="off">
                        <span asp-validation-for="DistrictName" class="invalid"></span>
                    </div>


                    <div class="mb-3">
                        <label asp-for="DistrictShort" for="UserName" class="form-label"></label>
                        <input type="text" asp-for="DistrictShort" class="form-control" maxlength="4" placeholder="Enter Short Name (max 10 characters)" autocomplete="off">
                        <span asp-validation-for="DistrictShort" class="invalid"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="DistrictCode" class="form-label required"></label>
                        <input type="text" asp-for="DistrictCode" onkeypress="return onlyNumber(event)" class="form-control" maxlength="3" placeholder="Enter District Code (max 3 digits number)" autocomplete="off">
                        <span asp-validation-for="DistrictCode" class="invalid"></span>
                    </div>

                    <div class="mb-2 text-end">
                        <a asp-area="" asp-controller="District" asp-action="Index" class="btn btn-light btn-sm"><i class="dripicons-reply m-1"></i> Back to list </a>
                        <button class="btn btn-primary btn-sm" type="submit"><i class="uil-weight me-1"></i> Update </button>
                    </div>
                </div>

            </div> <!-- end card -->
        </form>
    </div> <!-- end card body-->
</div>

CSRPulse/Views/District/Import.cshtml
@{
    ViewBag.Title = "Import District";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .modal-backdrop {
        /* bug fix - no overlay */
        display: none;
    }

    .error1 {
        background-color: #fa2d46 !important;
        color: white !important;
    }
</style>

<div class="row">

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="dv-Import-Section">

        <div class="panel panel-default">

            <div class="panel-body" id="dv-import">
                @{await Html.RenderPartialAsync("_ImportFilter");}

                <hr />
                <div id="xss" style="height:auto;">

                </div>

            </div>

        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(
        function () {
            $('input:file').change(
                function () {
                    if ($(this).val()) {
                        $('#submitform').attr('disabled', false);                         
                    }
                }
            );           
        });

    function onsuccess(data) {       
        if (data.status == "nofileFound") {

            $("#xss").html(data.htmlData);
                $('#waitLoading').css('display', 'none');
                $('.modal-backdrop').hide();

        }
        if (data.status == "inValidFileFormat") {

            $("#xss").html(data.htmlData);
                $('#waitLoading').css('display', 'none');
                $('.modal-backdrop').hide();

        }
        if (data.status == "noRecordFound") {

            $("#xss").html(data.htmlData);
                $('#waitLoading').css('display', 'none');
                $('.modal-backdrop').hide();

        }
        if (data.status == "success") {

            $("#xss").html(data.htmlData);
                $('#waitLoading').css('display', 'none');
                $('.modal-backdrop').hide();
        }

    }
</script>

<script>
        $('#btnSave').click(function () {           
            $.ajax({
                type: 'POST',
                dataType: 'JSON',
                url: '@Url.Action("Save", "District")',
                success: function (data) {
                    if (data.errorCode == -1)
                        $("#validation-hdr").html(data.error).addClass('alert alert-danger');
                    if (data.errorCode == 0) {
                        $("#validation-hdr").html(data.msg).addClass('alert alert-success');
                        $("#btnSave").addClass('d-none');
                    }
                    $('#waitLoading').css('display', 'd-none');
                    $('.modal-backdrop').hide();
                }
            });
        });

</script>

CSRPulse/Views/District/Index.cshtml
@{
    ViewData["Title"] = "District";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CSRPulse</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Masters</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Locations</a></li>
                    <li class="breadcrumb-item active">District</li>
                </ol>
            </div>
            <h4 class="page-title">District List</h4>
        </div>
    </div>
</div>

<div class="row">
    @{await Html.RenderPartialAsync("_Filter");}
</div>
<div id="div-district-list"></div>
<partial name="_Confirmation" />

@section Scripts{
    <script type="text/javascript">

        function openpopup(cnt) {
            debugger;
            var id = cnt.id.split('_')[1];
            $('.btnconfirm').attr('id', id + '_' + cnt.checked);

        }
        function ActiveDeActive(obj) {
            var id = obj.id.split('_')[0];
            var isChecked = obj.id.split('_')[1];
            $.ajax({
                type: 'POST',
                dataType: 'JSON',
                url: '/District/ActiveDeActive',
                headers: { "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val() },
                data: { id: id, isChecked: isChecked },
                success: function (responce) {
                    if (responce) {
                        commonMessage('success', 'Status changed successfully.');
                    }

                    else {
                        commonMessage('warning', 'Status changing failed.');
                    }
                },
                error: function (responce) {
                    commonMessage('error', 'Status changing failed.');
                }
            });
        }
    </script>
}

CSRPulse/Views/District/_DistrictList.cshtml
@model IEnumerable<District>
<div class="card">
    <div class="card-body">
        <div class="col-md text-end">
            <a asp-controller="District" asp-action="Create" class="btn btn-danger btn-sm btn-rounded mb-3"><i class="mdi mdi-plus-circle me-1"></i> Add New District</a>

            <div class="dropdown btn-group" style="vertical-align:top">
                <button class="btn btn-secondary btn-sm btn-rounded dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="dripicons-gear me-1"></i> Action
                </button>
                <div class="dropdown-menu dropdown-menu-animated">
                    <a class="dropdown-item" data-bs-toggle="tooltip" data-bs-placement="top" title="Download code refrence" asp-controller="District" asp-action="ExportRefTemplate"><i class="uil-file-download me-1"></i>Code Refrence</a>
                    <a class="dropdown-item" data-bs-toggle="tooltip" data-bs-placement="top" title="Download empty template" asp-controller="District" asp-action="ExportTemplate"><i class="uil-arrow-circle-down me-1"></i>Empty Template</a>
                    <a class="dropdown-item" data-bs-toggle="tooltip" data-bs-placement="top" title="Import template data" asp-controller="District" asp-action="Import"><i class="uil-arrow-circle-up me-1"></i>Import Data</a>
                </div>
            </div>
        </div>
        <table class="basic-datatable table table-hover dt-responsive nowrap w-100">
            <thead class="thead-light">
                <tr>
                    <th width="5%">#</th>
                    <th>@Html.DisplayNameFor(m => m.DistrictName)</th>
                    <th>@Html.DisplayNameFor(m => m.DistrictCode)</th>
                    <th>@Html.DisplayNameFor(m => m.DistrictShort)</th>
                    <th>@Html.DisplayNameFor(m => m.StateName)</th>
                    <th width="5%">Active</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() > 0)
                {
                    @foreach (var district in Model)
                    {
                        <tr>
                            <td>
                                <span>@(Model.ToList().IndexOf(district) +1)</span>
                            </td>

                            <td><span data-bs-toggle="tooltip" data-bs-placement="top" title="Click here, to edit this district.">  @Html.ActionLink(district.DistrictName, "Edit", "District", new { rid = district.DistrictId })</span></td>
                            <td>@district.DistrictCode</td>
                            <td>@district.DistrictShort</td>
                            <td>@district.StateName</td>
                            <td>
                                <div>
                                    <input type="checkbox" id="switch_@district.DistrictId" data-bs-toggle="modal" data-bs-target="#info-header-modal" onchange="openpopup(this)" data-switch="success" @if (district.IsActive == true) { <text> checked="checked" </text> } />
                                    <label for="switch_@district.DistrictId" data-on-label="Yes" data-off-label="No" class="mb-0 d-block"></label>
                                </div>
                            </td>
                        </tr>

                    }
                }
                else
                {
                    <tr>
                        <td colspan="6">No Records Found</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        Basicdatatable();
    });
</script>

CSRPulse/Views/District/_Filter.cshtml
@model District

<div class="card bg-transparent">
    <div class="card-body">
        <form data-ajax="true" data-ajax-method="GET" data-ajax-update="#div-district-list" data-ajax-mode="replace" asp-action="GetDistrictList" asp-controller="District">
            <div class="col-md-2 col-form-label">
                <i class="mdi mdi-filter"></i> <label>Filter By :</label>
            </div>

            <div class="row">
                <label asp-for="StateId" class="col-md-2 col-form-label"></label>
                <div class="col-md-4">
                    <select asp-for="StateId" asp-items="@ViewBag.ddlState" aria-required="true" class="form-select">
                        <option label="All" selected="" value=""></option>
                    </select>
                    <span asp-validation-for="StateId" class="invalid"></span>
                </div>

                <label asp-for="IsActiveFilter" class="col-md-1 col-form-label"></label>
                <div class="col-md-3">
                    <select asp-for="IsActiveFilter" aria-required="true" class="form-select">
                        <option label="All" selected="" value=""></option>
                        <option label="Yes" value="true"></option>
                        <option label="No" value="false"></option>
                    </select>
                    <span asp-validation-for="IsActiveFilter" class="invalid"></span>
                </div>
                <div class="col-md-2 text-end">
                    <button type="submit" value="Search" data-bs-toggle="tooltip" data-bs-placement="top" title="Click here, to search records" class="btn btn-warning btn-sm rounded-pill text-white">
                        <i class="dripicons-search me-2"></i> Search
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

CSRPulse/Views/District/_ImportFilter.cshtml
<form data-ajax="true" data-ajax-method="post" asp-controller="District" asp-action="_ImportDistrictData" enctype="multipart/form-data" data-ajax-success="onsuccess">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-1 mt-2">

        <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-1 col-sm-12 col-xs-12 required mt-2">
                Select File
            </div>
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-xs-12">

                <div class="input-group image-preview">
                    <input type="text" class="form-control image-preview-filename" disabled="disabled"> <!-- don't give a name === doesn't send on POST/GET -->
                    <span class="input-group-btn">
                        <!-- image-preview-clear button -->
                        <button type="button" class="btn btn-default image-preview-clear" style="display:none;">
                            <span class="glyphicon glyphicon-remove"></span> Clear
                        </button>
                        <!-- image-preview-input -->
                        <span class="btn btn-default image-preview-input">
                            <span class="glyphicon glyphicon-folder-open"></span>
                            <span class="image-preview-input-title">Browse</span>
                            @Html.TextBox("file", "", new { type = "file", @class = "", @name = "input-file-preview" })
                        </span>
                    </span>
                </div>
                <div>
                    @Html.ValidationMessage("FileRequired", "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 col-xs-12">

                <button type="submit" id="submitform" class="btn btn-success pull-center validate-data"
                        data-toggle="tooltip"
                        title="Click here, to validate your file." disabled>
                    <i class="dripicons-checkmark me-1" aria-hidden="true"></i>
                    Validate Data
                </button>
            </div>

            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 col-xs-12">
                <button type="button" id="btnSave" class="btn btn-info pull-center d-none"
                        data-toggle="tooltip" title="Click here, to update manual sheet data.">
                    <i class="dripicons-cloud-upload me-1" aria-hidden="true"></i>
                    Import Data
                </button>
            </div>
        </div>
    </div>
</form>