CSRPulse/Controllers/ProcessWorkFlow/ProcessWorkFlowController.cs
using CSRPulse.Model;
using CSRPulse.Models;
using CSRPulse.Services;
using CSRPulse.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CSRPulse.Controllers
{
    public class ProcessWorkFlowController : BaseController<ProcessWorkFlowController>
    {
        private readonly IProcessSetupServices _processSetupServices;
        private readonly IDropdownBindService _dropdownBindService;

        public ProcessWorkFlowController(IProcessSetupServices processSetupServices, IDropdownBindService dropdownBindService)
        {
            _processSetupServices = processSetupServices;
            _dropdownBindService = dropdownBindService;
        }
        public IActionResult Index()
        {
            ProcessSetupModel processSetup = new ProcessSetupModel();
            var process = _dropdownBindService.GetProcess(null);
            ViewBag.ddlProcess = new SelectList(process, "id", "value");
            return View();
        }

        public async Task<PartialViewResult> GetProcessWorkFlow(int processId)
        {
            _logger.LogInformation("ProcessWorkFlow/GetProcessWorkFlow");

            ViewBag.ddlRole = new SelectList(_dropdownBindService.GetRole(null), "id", "value");

            ViewBag.ddlRevisionNo = new SelectList(await _processSetupServices.GetRevisionHistoryDropdown(processId), "id", "value");

            var setupModel = new ProcessSetupModel();

            var processes = await _processSetupServices.GetProcessSetupById(processId);

            if (processes != null && processes.Count > 0)
                setupModel.RevisionNo = GetRevisionNo(processes, processId);
            else
                setupModel.RevisionNo = 1;
            setupModel.ProcessId = processId;

            setupModel.processSetupList = MakeProcesRecords(processes, processId, setupModel.RevisionNo);
            return PartialView("_WorkFlowList", setupModel);
        }

        public async Task<IActionResult> UpdateSkipValue(ProcessSetupModel processSetup)
        {
            _logger.LogInformation("ProcessWorkFlow/UpdateSkipValue");
            try
            {
                bool result = false;
                if (processSetup.processSetupList != null)
                {
                    foreach (var process in processSetup.processSetupList)
                    {
                        process.UpdatedBy = userDetail.UserID;
                        process.UpdatedOn = DateTime.Now;
                        process.UpdatedRid = userDetail.RoleId;
                        process.UpdatedRname = userDetail.RoleName;
                        result = await _processSetupServices.UpdateProcessSetup(process);
                    }
                }

                return Json(new { success = result, htmlData = ConvertViewToString("_WorkFlowList", processSetup, true) });
            }
            catch (Exception ex)
            {
                _logger.LogError($"Message-" + ex.Message + " StackTrace-" + ex.StackTrace + " DatetimeStamp-" + DateTime.Now);

                throw;
            }
        }
        public async Task<IActionResult> UpdateProcessWorkflow(ProcessSetupModel processes)
        {
            _logger.LogInformation("ProcessWorkFlow/UpdateSkillValue");
            try
            {
                var listProces = processes.processSetupList.Where(s => s.PrimaryRoleId > 0 && s.LevelId > 0).ToList();
                if (listProces.Count > 0)
                {
                    var CreatedOn = DateTime.Now;
                    listProces.ToList().ForEach(h =>
                    {
                        h.CreatedOn = CreatedOn;
                        h.CreatedBy = userDetail.UserID;
                        h.CreatedRid = userDetail.RoleId;
                        h.CreatedRname = userDetail.RoleName;
                    });

                    var result = await _processSetupServices.CreateProcessSetup(listProces);

                    return Json(new { success = result, msg = 1, htmlData = ConvertViewToString("_WorkFlowList", processes, true) });
                }
                else
                {
                    return Json(new { success = false, msg = 0, htmlData = ConvertViewToString("_WorkFlowList", processes, true) });
                }


            }
            catch (Exception ex)
            {
                _logger.LogError($"Message-" + ex.Message + " StackTrace-" + ex.StackTrace + " DatetimeStamp-" + DateTime.Now);

                throw;
            }
        }


        public async Task<ActionResult> ProcessSetupHistory(int processId, int revisionNo)
        {
            var processSetupHistory = await _processSetupServices.GetPSHistoryDetails(processId, revisionNo);
            return PartialView("_ProcessSetupHistory", processSetupHistory);
        }

        private List<ProcessSetup> MakeProcesRecords(List<ProcessSetup> processSetups, int processId, int revisionNo)
        {
            for (int i = processSetups.Count; i < 6; i++)
            {
                processSetups.Add(new ProcessSetup
                {
                    ProcessId = processId,
                    RevisionNo = revisionNo,
                    Sequence = (i + 1)

                });
            }
            return processSetups.OrderBy(s => s.Sequence).ToList();
        }


        private int GetRevisionNo(List<ProcessSetup> processSetups, int processId)
        {
            return processSetups.Where(w => w.ProcessId == processId).Select(r => r.RevisionNo).FirstOrDefault();
        }
    }
}

CSRPulse/Views/ProcessWorkFlow/Index.cshtml
@model CSRPulse.Models.ProcessSetupModel
@{
    ViewData["Title"] = "Process Work Flow";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">CSRPulse</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Masters</a></li>
                    <li class="breadcrumb-item active">Process Workflow</li>
                </ol>
            </div>
            <h4 class="page-title">Process Workflow</h4>
        </div>
    </div>
</div>

<div class="row">
    @{await Html.RenderPartialAsync("_Filter",Model);}
</div>
<div id="div-workflow-list">

</div>

CSRPulse/Views/ProcessWorkFlow/_Filter.cshtml
@model ProcessSetupModel

<div class="card bg-transparent">
    <div class="card-body">
        <form data-ajax="true" data-ajax-method="GET" data-ajax-update="#div-workflow-list" data-ajax-mode="replace" asp-action="GetProcessWorkFlow" asp-controller="ProcessWorkFlow">
            <div class="col-md-2 col-form-label">
                <i class="mdi mdi-filter"></i> <label>Filter By :</label>
            </div>

            <div class="row">
                <label asp-for="ProcessId" class="col-md-1 col-form-label">Process</label>

                <div class="col-md-5">
                    <select asp-for="ProcessId" asp-items="@ViewBag.ddlProcess" aria-required="true" class="form-select">
                        <option label="Select Process" disabled selected="" value=""></option>
                    </select>
                    <span asp-validation-for="ProcessId" class="invalid"></span>

                </div>
                <div class="col-md-6 text-end">
                    <button type="submit" value="Search" data-bs-toggle="tooltip" data-bs-placement="top" title="Click here, to search records" class="btn btn-warning btn-sm rounded-pill text-white">
                        <i class="dripicons-search me-1"></i> Search
                    </button>
                </div>

            </div>
        </form>
    </div>
</div>

CSRPulse/Views/ProcessWorkFlow/_ProcessSetupHistory.cshtml
@model IEnumerable<ProcessSetupHistory>
@using CSRPulse.Common
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <table class="table table-hover table-centered mb-0">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th>Skip</th>
                    <th>Primary Role</th>
                    <th>Secondory Role</th>
                    <th>Tertiary Role</th>
                    <th>Quaternary Role</th>
                    <th>Level Name</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Count() > 0)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <span>@(Model.ToList().IndexOf(item) +1)</span>
                            </td>
                            <td><span class="badge @(item.Skip==true?"bg-success":"bg-danger")">@ExtensionMethods.BoolToYesNo(item.Skip ?? false)</span></td>
                            <td>@item.PrimaryRole</td>
                            <td>@item.SecondoryRole</td>
                            <td>@item.TertiaryRole</td>
                            <td>@item.QuaternaryRole</td>
                            <td>@Enum.GetName(typeof(ProcessLevel), item.LevelId)</td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="6">No Records Found</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>